title: JekFolio
markdown: kramdown
url: ""
baseurl: "/jekyll-theme-jekfolio"

# for atom feed
author:
  name: Sharad Raj
  email: dev_sharad@outlook.com
  profile-image: profile.jpg
  bio:  Developer | CS Student

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

paginate_path: "/page:num/"

paginate: 5

defaults:
  - scope:
      path: ""
    values:
      layout: "post"


exclude: ['sitemap.xml','feed.xml', 'LICENSE', 'README.md']